#!/bin/bash

# Send all errors to stdout
exec 2>&1

# Print MIME type
cat <<MIME
Content-Type: text/html

MIME

# HTML header
stamp=$(date)
cat <<HEADER
<!-- $stamp -->

<html>
<head>
<meta http-equiv="refresh" content="1">
</head>
<body>
<pre>
HEADER

# object=/tmp/wifi.o
# clang++ /home/deanturpin/dev/watch/wifi.cpp -o $object -std=c++1z && $object

pushd /home/deanturpin/dev/watch >& /dev/null
make run
popd >& /dev/null

# HTML footer
cat <<FOOTER
</pre>
</body>
FOOTER

