#!/bin/bash

# Look up vendor from first half of MAC
function vendor {

	# If a MAC matches then look up the vendor
	if [[ $* =~ ([[:xdigit:]]{2}:){5}[[:xdigit:]]{2} ]]; then

		# Strip colons
		mac=${BASH_REMATCH//:/}

		# Look up the vendor using the first half of the MAC
		v=$(grep -i ${mac:0:6} /usr/share/ieee-data/oui.txt)

		# Print if not empty (strip leading repeated info)
		[[ $v != '' ]] && echo ${v#*)}
	fi
}

# Pretty print a header for each section
function header {
	echo -e \\n$*
	echo '----------'
}

# Trim and strip quotes
function trim_ap {
	ap=${*#*:}
	echo ${ap//\"/}
}

# Print something that changes each time
date

header Current access point
trim_ap $(iwgetid)

external=8.8.8.8
header Ping $external
ping -w 1 -c 1 $external >& /dev/null && echo success || echo fail

header Routing table
ip route

header MAC/vendor for IPs on the subnet
ip n | while read line; do
	vendor $line
done

header Portscan self
nc -vz 0.0.0.0 1-10000 |& grep succeeded

header Visible access points
iwlist wlp1s0 scan | while read line; do

	[[ $line =~ Cell ]] && echo -e \\n$line && vendor $line
	[[ $line =~ 'Encryption key:off' ]] && echo OPEN
	[[ $line =~ ESSID ]] && trim_ap $line
done
