#!/bin/bash

# Look up vendor from first half of MAC
function vendor {

	# If a MAC matches then look up the vendor
	if [[ $line =~ ([[:xdigit:]]{2}:){5}[[:xdigit:]]{2} ]]; then
		mac=$BASH_REMATCH
		echo -n $mac \-\ 

		# Strip colons
		mac=${mac//:/}

		# Look up the vendor using the first half of the MAC
		vend=$(grep -i ${mac:0:6} /usr/share/ieee-data/oui.txt)

		if [[ $vend != '' ]]; then
			echo \- ${vend##)*}
		else
			echo no vendor
		fi
	fi
}

function header {
	echo -e \\n$*
	echo '----------'
}

header Current access point
ap=$(iwgetid)

# Trim and strip quotes
ap=${ap#*:}
echo ${ap//\"/}

external=8.8.8.8
header Ping $external
ping -w 1 -c 1 $external >& /dev/null && echo success || echo fail

header Available NICs
ls /sys/class/net/

header My MAC/vendor
mac=$(cat /sys/class/net/wlp1s0/address)
echo $mac \- $(vendor $mac)

header Routing table
ip route

header MAC/vendor for visible access points
iwlist wlp1s0 scan | while read line; do
	vendor $line
done

header MAC/vendor for IPs on the subnet
ip n | while read line; do
	vendor $line
done

header Portscan self
nc -vz 0.0.0.0 1-10000 |& grep succeeded

# header TCP dump
# tcpdump | head
