#!/bin/bash

# Send all errors to stdout
exec 2>&1

# Print MIME type
cat <<MIME
Content-Type: text/plain

MIME

# Check params
[[ $QUERY_STRING == "" ]] && echo What shall I watch? && exit

# Strip %
command=${QUERY_STRING//%20/ }

# Run the command
$command
